version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: root
    volumes:
      - "./observability/prometheus/:/etc/prometheus/"
      - "./observability/prometheus/data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=true
    ports:
      - "3000:3000"
    volumes:
      - "./observability/grafana/data:/var/grafana/grafana_data"
      - "./observability/grafana/provisioning/:/etc/grafana/provisioning/"

  db:
    container_name: pg-example-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  migrator:
    container_name: migrator
    depends_on:
      - db
    build:
      dockerfile: docker/migrator/Dockerfile
    links:
      - db

  example:
    container_name: example
    build:
      dockerfile: docker/example/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    links:
      - migrator

#  alertmanager:
#    image: prom/alertmanager
#    ports:
#      - "9093:9093"
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    command:
#      - "--config.file=/etc/alertmanager/config.yml"
#      - "--storage.path=/alertmanager"

# https://github.com/rubencougil/prometheus-go/blob/master/README.md
