db.postgres.book.host = "localhost"
db.postgres.book.port = 5432
db.postgres.book.name = "postgres"
db.postgres.book.user = "postgres"
db.postgres.book.password = "password"
db.postgres.book.ssl = "disable"
db.postgres.book.connMaxLifetime = "180s"
db.postgres.book.maxOpenConns = 10
db.postgres.book.connMaxIdleTime = "240s"
db.postgres.book.maxIdleConns = 5